language: ruby
cache: bundler
rvm:
- 2.1.1
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database sample_app_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Gsq2yhUqhbBezvtaRTUXYO19KUAPv2+q+3050PnjPmMYJp4wgIRavDGET8q3SLuirHtkyjjmUFbqKgp7ciAH9gqMOdJZpdx5j5Sdm0kEPDv5hmJMQk5XrCtSZUUxREOtc6JOr/P0g8Ryhm/75sbY6wUGJCi97NU995V/2zCgP0g=
  app: salty-garden-6583
addons:
  code_climate:
    repo_token: 757f2c6e1b65aad393cf4427200f5e41e542040612a01148c8125f2404da2e80
